### ISSUE TITLE
Package with the same name in CRAN

### ISSUE THREAD

**Issue by FVFaleiro** [danicat/datasus#5]
Great work, but there is a package in CRAN to do the same things (https://cran.r-project.org/web/packages/datasus/).

**Comment by danicat** [comment]
Mine is older :)

I wish the author had reached out to me before starting his own project submitting it to CRAN, because he could have continued the work I've started and we wouldn't divide the community. 

Nevertheless both packages take completely different approaches:  my package access the data in binary format from the DATASUS ftp and his uses web scrapping.

I won't say it's better to use mine, actually quite the opposite. It's best for you to use his because I'm not having the time to actually maintain and improve this one. 

Hopefully his package will be evolving faster and you'll be better supported using the one available at CRAN.
